version: "3"
services:
  web:
    image: uconn/php72-official
    environment:
      SITE_ENV: local
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./:/var/www/html/content/plugins/uconn-banner-wp
    depends_on:
      - mysql
  mysql:
    image: uconn/comm0db:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
